### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ajasja** [RosettaCommons/pyrosetta_viewer3d#2]
When I try to install `python setup.py develop` I get the error

```
running develop
running egg_info
creating viewer3d.egg-info
writing viewer3d.egg-info/PKG-INFO
writing dependency_links to viewer3d.egg-info/dependency_links.txt
writing top-level names to viewer3d.egg-info/top_level.txt
writing manifest file 'viewer3d.egg-info/SOURCES.txt'
error: package directory 'ipywidgets>=7/5/1' does not exist
```
![image](https://user-images.githubusercontent.com/19926/171856913-1c26bf0e-91ae-41cb-83ed-e0ca53d49674.png)

Not sure where this is coming from

**Comment by ajasja** [comment]
Or in @klimaj branch 
![image](https://user-images.githubusercontent.com/19926/171858094-68f013bf-0fde-4680-b3dc-5df887fa016d.png)

**Comment by ajasja** [comment]
I think `python setup.py develop` should install py3dmol as well...

**Comment by klimaj** [comment]
I'm not sure where the slashes are coming from? The `setup.py` package dependencies are:
```
    packages=[
        "attrs>=18.2.0",
        "ipywidgets>=7.5.1",
        "jupyter>=1.0.0",
        "numpy>=1.18.1",
        "py3Dmol>=1.8.0",
        "pyrosetta>=2022.21",
    ],
```
(note the `.`s instead of `/`s)

**Comment by ajasja** [comment]
Thanks, yes, I did take a look. Not sure where the slashes are coming from either. Will test again today.

**Comment by ajasja** [comment]
Strange, I'm still getting the same error 
![image](https://user-images.githubusercontent.com/19926/172118224-e58e345c-4ea3-44b3-bdb5-d36f968cab32.png)

**Comment by ajasja** [comment]
The error is demonstrated in this colab notebook
https://colab.research.google.com/drive/16sMs25Oh2ESZfISK5iw0NOOU1mwCjvBT?usp=sharing#scrollTo=V6AyHiZUpfxO

**Comment by ajasja** [comment]
Should be fixed by https://github.com/RosettaCommons/pyrosetta_viewer3d/pull/6
