### ISSUE TITLE
Enable commit squashing

### ISSUE THREAD

**Issue by ajasja** [RosettaCommons/pyrosetta_viewer3d#5]
@klimaj Could you enable commit squashing? 
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by klimaj** [comment]
Yes, it should be set!
![Screen Shot 2022-06-07 at 1 16 36 PM](https://user-images.githubusercontent.com/7121657/172474385-da04d044-9460-4603-a8ed-3b0d99475acd.png)

**Comment by ajasja** [comment]
Thanks!
